routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@actionIndex');
Route::get('/search', 'MainController@actionSearch');

Route::group(['prefix' => '/correlation', 'namespace' => 'Correlation'], function (){
    Route::get('/', 'CorrelationController@actionIndex');
    Route::get('/search', 'CorrelationController@actionSearch');
});

app/Http/Controllers/Correlation/CorrelationController.php
<?php

namespace App\Http\Controllers\Correlation;
use Illuminate\Http\Request;
use DB;
use App\Models\AuxilaryWord;
use App\Models\MergeWord;
use App\Models\MetaData;
use App\Models\Word;
use App\Http\Controllers\Controller;

class CorrelationController extends Controller
{

    private $dataSet;

    public function __construct()
    {
        $this->dataSet = $this->initMetaData();
    }

    public function actionIndex()
    {
        return view('correlation.index');
    }

    public function actionSearch(Request $request)
    {
        $keyword = $request->get('keyword');
        $page = $request->get('p');
        if(is_null($page)){
            $page = 1;
        }

        try{
            $result = $this->mining($keyword, $page);
            $totalPage = $result['totalData'];
            if($totalPage > 0 && $totalPage <= 5){
                $totalPage = 1;
            }elseif ($totalPage > 5){
                $tmpTotalPage = floor($totalPage / 5);
                if($totalPage %5 > 0){
                    $tmpTotalPage += 1;
                }

                $totalPage = $tmpTotalPage;
            }

            $result = $result['data'];

        }catch (\Exception $e){
            $result = [];
            $totalPage = 0;
        }

        $params = [
            'keyword' => $keyword,
            'data' => $result,
            'p' => $page,
            'totalPage' => $totalPage
        ];
        return view('correlation.search', $params);


    }

    private function mining($keyword, $page)
    {
        $splitedWord = explode(" ",$keyword);
        $result = $this->analyzingProcess($splitedWord);
        $filterId = [];
        $stringOrderd = "";
        $offset = 5 * ($page - 1);

        foreach ($result as $num => $item)
        {
            if($item['degree'] > 0.0){
                $filterId[] = $item['metadata_id'];
            }
        }

        $totalData = count($filterId);
        $selectedData = 0;
        foreach ($filterId as $num => $item){
            if($selectedData < 5){
                if($totalData > 5){
                    if($num < $offset){
                        continue;
                    }else{
                        $stringOrderd .= $item;
                        $stringOrderd .= ",";
                    }
                }else{
                    if($totalData <= 5  && $offset <= $totalData){
                        $stringOrderd .= $item;
                        $stringOrderd .= ",";
                    }elseif($totalData <= 5  && $page == 1){
                        $stringOrderd .= $item;
                        $stringOrderd .= ",";
                    }
                }
            }
            $selectedData++;
        }

        $stringOrderd .= "0";

        $resultData = MetaData::whereRaw("id IN (".$stringOrderd.")")
            ->get()->toArray();


        $displayedData = [];
        foreach ($resultData as $item) {
            $index = array_search($item['id'], $filterId);
            $displayedData[$index] = $item;
        }

        $displayedData = collect($displayedData)->sortKeys();

        $params = [
            'data' => $displayedData,
            'totalData' => $totalData
        ];

        return $params;
    }

    private function analyzingProcess($sourceKeywords)
    {
        $data = [];
        foreach ($this->dataSet as $num => $content) {
            $templateScore = $this->initScoringTemplate($sourceKeywords);
            $splitedContentData = explode(" ", strtolower($content->content));
            foreach ($sourceKeywords as $no => $item){
                if(in_array(strtolower($item), $splitedContentData)){
                    $templateScore[$item]['score'] = 1;
                }
            }

            $data[] = [
                'metadata_id' => $content->id,
                'data' => $content,
                'result' => $templateScore
            ];
        }

        $result = $this->calculateSimiliarity($data);


        return $result;
    }

    private function calculateSimiliarity($data)
    {
        $result = [];
        foreach ($data as $num => $item) {
            $tempValue = [];
            $tempScore = 0;
            foreach ($item['result'] as $no => $value){
                $score = $value['score'] * 1;
                $tempValue[$value['label']] = $score;
                $tempScore += $score;

                $cosine = $this->cosineSimiliarity($tempScore, $tempValue);
            }

            $result[] = [
                'metadata_id' => $item['metadata_id'],
                'data' => $item['data'],
                'result' => $tempValue,
                'score' => $cosine,
                'degree' => number_format(rad2deg($cosine), 2)
            ];
        }

        $response = $this->customeArraySorter($result);
        return $response;
    }

    private function customeArraySorter($template)
    {
        array_multisort(array_map(function($element) {
            return $element['degree'];
        }, $template), SORT_DESC, $template);

        return $template;
    }

    private function cosineSimiliarity($tempScore, $arrayValue)
    {
        $totalPowX = 0;
        $totalPowY = 0;
        foreach ($arrayValue as $num => $value)
        {
            $powX = pow(1, 2);
            $powY = pow($value, 2);

            $totalPowX += $powX;
            $totalPowY += $powY;
        }

        $dividen = sqrt($totalPowX) + sqrt($totalPowY);
        if($tempScore == 0 || $dividen == 0){
            $result = 0;
        }else{
            $result = $tempScore / $dividen;
        }

        return $result;
    }

    private function initScoringTemplate($data)
    {
        $template = [];
        foreach ($data as $num => $item) {
            $template[$item] = [
                'label' => $item,
                'score' => 0
            ];
        }

        return $template;
    }

    private function initMetaData()
    {
        return MetaData::all();
    }
}

resources/views/correlation/index.blade.php
<html>
<head>
    <title>@yield('title')</title>
    <link a href="{{asset('public/assets/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <script src="{{asset('public/js/jquery-2.0.3.min.js')}}"></script>
    <script src="{{asset('public/assets/bootstrap/js/bootstrap.min.js')}}"></script>
</head>
<style>
    body {
        font-family: sans-serif;
    }

    .content-box {
        padding: 10%;
    }

    .custom-button {
        min-width: 150px;
        margin: 5px;
    }

    .custom-color {
        background: white;
        border: none;
    }

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        padding: 8px;
        background-color: #f2f2f2;
    }
</style>
<body>
<nav class="navbar navbar-default custom-color navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><br></a>
        </div>

        <ul class="nav navbar-nav navbar-right" style="padding: 5px;">
            <li><a href="#"> DSMail</a></li>
            <li><a href="#"> Gambar</a></li>
            <li>
                <a href="#">
                    <span class="glyphicon glyphicon-th"></span>
                </a>
            </li>
            <li></li>
            <li>
                <img src="{{asset('public/img/profile.png')}}" style="padding: 1px" width="35" height="35" class="img-circle">
            </li>
        </ul>
    </div>
</nav>

<div class="col-xs-12" style="margin-top: 80px;">
    <div class="row">
        <div class="container content-box">
            <p align="center">
                <span class="glyphicon glyphicon-search" style="font-size: 80px;"></span>
                <br>
                <span style="font-size: 25px;">DreamSearch</span>
            </p>
            <form method="GET" action="{{url('/correlation/search')}}" id="form-konten">
                <input type="text" name="keyword" id="keyword" placeholder="Type here..." class="form-control" style="padding: 20px;">

                <p align="center" style="margin-top: 20px;">
                    <button type="submit" id="submit-button" class="btn btn-default custom-button" disabled>
                        DreamSearch
                    </button>

                    <input type="reset" class="btn btn-default custom-button" value="Reset">
                </p>
            </form>

            <p align="center">
                DreamSearch offered in : <a href="#">Indonesia</a>
            </p>

        </div>
    </div>
</div>

<div class="footer">
    <p>Indonesia</p>
</div>

<script>
    $(document).ready(
        function() {
            $('#keyword').keypress(
                function() {
                    var value = document.getElementById('keyword').value;
                    if (value.length > 0) {
                        $('#submit-button').prop("disabled", false);
                    }
                });

            $('#keyword').keydown(
                function() {
                    var value = document.getElementById('keyword').value;
                    if (value.length < 2) {
                        $('#submit-button').prop("disabled", true);
                    }
                });
        });
</script>

</body>
</html>

resources/views/correlation/search.blade.php
<html>
<head>
    <title>@yield('title')</title>
    <link a href="{{asset('public/assets/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    <script src="{{asset('public/js/jquery-2.0.3.min.js')}}"></script>
    <script src="{{asset('public/assets/bootstrap/js/bootstrap.min.js')}}"></script>
</head>
<style>
    body {
        font-family: sans-serif;
    }

    .content-box {
        padding: 10%;
    }

    .custom-button {
        min-width: 150px;
        margin: 5px;
    }

    .custom-color {
        background: white;
        border: none;
    }

    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        padding: 8px;
        background-color: #f2f2f2;
    }
</style>
<body>
<nav class="navbar navbar-default navbar-fixed-top" style="padding: 20px;">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{url('/')}}">
                <span class="glyphicon glyphicon-search" style="font-size: 20px;"></span>
                <span style="font-size: 20px;">DreamSearch</span>
            </a>
        </div>

        <ul class="nav navbar-nav">
            <li>
                <form method="GET" action="{{url('/correlation/search')}}" id="form-konten">
                    <input type="text" name="keyword" id="keyword" value="{{$keyword}}" placeholder="Type here..." class="form-control" style="padding: 20px; width: 450px;">
                </form>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right" style="padding: 5px;">
            <li>
                <a href="#">
                    <span class="glyphicon glyphicon-th"></span>
                </a>
            </li>
            <li></li>
            <li>
                <img src="{{asset('public/img/profile.png')}}" style="padding: 1px" width="35" height="35" class="img-circle">
            </li>
        </ul>
    </div>
</nav>

<br><br>
<div class="col-xs-12" style="margin-top: 100px;">
    <div class="row">
        <div class="container">
            @if(count($data) == 0)
                <p>
                    Your search <b>{{$keyword}}</b> - did not match any documents.
                    <br>
                    Suggestions:
                <li>Make sure that all words are spelled correctly.</li>
                <li>Try different keywords.</li>
                <li>Try more general keywords.</li>
                </p>
            @else
                @foreach($data as $num => $item)
                    <div class="row">
                        <div class="col-xs-12">
                            <h4>
                                <a href="{{$item['url']}}">
                                    {{$item['title']}}
                                </a>
                            </h4>
                            <span style="color: green;">{{$item['url']}}</span>
                            <p align="justify">
                                {{substr($item['content'], 0, 300)}} ...
                            </p>
                        </div>
                    </div>
                    <br>
                @endforeach

                <br><br>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        @for($i = 1; $i <= $totalPage; $i++)
                            <li class="page-item"><a class="page-link" href="{{url('/correlation/search?keyword=')}}{{$keyword}}&p={{$i}}">{{$i}}</a></li>
                        @endfor
                    </ul>
                </nav>

            @endif
        </div>
    </div>
</div>
</body>
</html>